---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: navidrome
resources:
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- pv.yaml
- pvc.yaml
- service.yaml
secretGenerator:
- name: navidrome-secrets
  envs:
  - .env
