apiVersion: v1
kind: Service
metadata:
  name: yamtrack-service
  namespace: yamtrack
spec:
  type: ClusterIP
  selector:
    app: yamtrack
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

