---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mopidy
resources:
- config-map.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
secretGenerator:
- name: mopidy-config
  files:
  - mopidy.conf
