apiVersion: v1
kind: Service
metadata:
  name: mopidy-service
  namespace: mopidy
spec:
  selector:
    app: mopidy
  ports:
    - protocol: TCP
      port: 6680
      targetPort: 6680
  externalIPs:
    - 192.168.1.252
---
apiVersion: v1
kind: Service
metadata:
  name: snapcast-service
  namespace: mopidy
spec:
  selector:
    app: mopidy
  ports:
    - protocol: TCP
      port: 1704
      targetPort: 1704
      name: stream-acceptor # Got this name from the logs
    - protocol: TCP
      port: 1705
      targetPort: 1705
      name: control-acceptor # Got this name from the logs
    - protocol: TCP
      port: 1780
      targetPort: 1780
      name: http
    - protocol: TCP
      port: 1788
      targetPort: 1788
      name: https
  externalIPs:
    - 192.168.1.252
